/* *
 * We create a language strings object containing all of our strings.
 * The keys for each string will then be referenced in our code, e.g. handlerInput.t('WELCOME_MSG').
 * The localisation interceptor in index.js will automatically choose the strings
 * that match the request's locale.
 * */

module.exports = {
    en: {
        translation: {
            WELCOME_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Welcome to Millionaire Monkeys. This game is about solving questions on various skills. You will get 15 questions and 3 life lines to help you while playing. To start a new game you can say, start new game, to start a group, or, play in a group say, create a new group, followed by group name, or, play in existing group, followed by group name.  To hear about the Life Lines in this game, say, Life Lines. For help, say , Help me. So, What can I help you with?</lang></voice>',
            WELCOME_BACK_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Welcome back to Millionaire Monkeys. To resume your previous game say, resume game. To start a new game, say, Start new Game. To play in a group say, create a new group, followed by group name, or, play in existing group, followed by group name.  For help, say , Help me. So, What can I help you with?</lang></voice>',
            WELCOME_REPROMPT_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> I didn\'t catch that. What can I help you with?</lang></voice>',
            GOODBYE_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Goodbye! Thank you for playing Millionaire Monkeys</lang></voice>',
            REFLECTOR_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> You just triggered {{intentName}}</lang></voice>',
            FALLBACK_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Sorry, I don\'t know about that. Please try again.</lang></voice>',
            ERROR_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Sorry, I had trouble doing what you asked. Please try again.</lang></voice>',
            CANNOT_BUY_RIGHT_NOW: '<voice name="Brian"><lang xml:lang="en-GB"> I don\'t think we have a product by that name.  Can you try again?</lang></voice>',
            START_QUIZ_MESSAGE: '<voice name="Brian"><lang xml:lang="en-GB"> OK.  Let\'s begin \'Millionaire Monkeys\' . </lang></voice>',
            CANNOT_CANCEL_RIGHT_NOW: '<voice name="Brian"><lang xml:lang="en-GB"> There was a problem while cancelling this purchase. Please try again after some times.</lang></voice>',
            ERROR_QUESTION_FETCH: '<voice name="Brian"><lang xml:lang="en-GB"> Sorry there was an error retrieving the questions. Please say resume game or start a new game to continue! Or Please try again after some times</lang></voice>',
            QUESTION_BEGIN: '<voice name="Brian"><lang xml:lang="en-GB"> To answer the question please say, answer is, and then your answer, Here is your question coming up now. </lang></voice>',
            ALL_QUESTIONS_ANSWERED: '<voice name="Brian"><lang xml:lang="en-GB"> Congratualtions! You have answered all the questions. You are a Millionaire Monkey. Well Done!  </lang></voice>',
            QUESTIONS_ANSWERED_CORRECTLY: '<voice name="Brian"><lang xml:lang="en-GB"> This is the right answer. </lang></voice>',
            QUESTIONS_ANSWERED_WORNG: '<voice name="Brian"><lang xml:lang="en-GB"> OH NO!    This     is     the      WRONG     answer.  </lang></voice>',
            NEXT_QUESTION: '<voice name="Brian"><lang xml:lang="en-GB"> Let us proceed to your next question. </lang></voice>',
            QUESTIONS_JUMP: '<voice name="Brian"><lang xml:lang="en-GB"> You can still buy and use your glide life line. If you want to glide over this question, please say buy GLIDE  life  line. </lang></voice>', 
            QUESTIONS_CANNOT_JUMP: '<voice name="Brian"><lang xml:lang="en-GB"> Unfortunately you have already used your GLIDE  life  line before. This game is ended .  Please start a new game. </lang></voice>', 
            QUESTIONS_REPROMPT_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> I didn\'t catch that.</lang></voice>' ,
            HELP_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> You can use Fifty  Fifty option to listen to couple of answers one right and another worng. ' 
            + ' Your another life line Expert Opinion can provide you some guidance for the correct answer. '
            + ' The third life line GLIDE can take you through an incorrect answers, but you need to buy GLIDE PACK </lang></voice>',
            CURRENT_SCORE: '<voice name="Brian"><lang xml:lang="en-GB"> Your current score is {{score}} . </lang></voice>',
            CURRENT_SCORE_ERROR: '<voice name="Brian"><lang xml:lang="en-GB"> Please resume or start a game to know the game score. </lang></voice>',
            FIFTY_FITY_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Here are the two options for your question. </lang></voice>',
            EXPERT_REVIEW_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> This is what expert has to say about your question. </lang></voice>',
            LIFE_LINE_ERROR_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Sorry, you can only use this life line when your game is in progress. Please resume or start a new game to use your life lines. </lang></voice>',
            LIFE_LINE_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> You have {{lifeLinesLeft}} life lines left. </lang></voice>',
            LIFE_LINE_EXHAUSTED: '<voice name="Brian"><lang xml:lang="en-GB"> Sorry, You have already used {{lifeLineName}} life line. Please use another life line. </lang></voice>',
            LIFE_LINES_SATUS: '<voice name="Brian"><lang xml:lang="en-GB"> To know about other life lines say my life line or life lines status. </lang></voice>',
            CURRENT_QUESTION: '<voice name="Brian"><lang xml:lang="en-GB">Here is your current question {{currentQuestion}} </lang></voice>',
            START_GAME_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> To resume your previous game say, \'resume game\', or to start a new game, say, \'Start new Game\'.  For help, say , \'Help me\'. So, What can I help you with?</lang></voice>',
            GAME_RULES_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> This game is about solving questions on various skills. You will get 15 questions and 3 life lines to help you while playing. </lang></voice>',
            USE_LIFE_LINES: '<voice name="Brian"><lang xml:lang="en-GB"> At any point of time you can say use Fifty Fifty or use Expert Review or Buy Glide life line </lang></voice>',
            RESUME_ERROR_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Sorry there are no games to resume. To start a new game, say \'Start new Game\'.  For help, say , \'Help me\'. So, What can I help you with?</lang></voice>',
            CONSUMABLE_NOT_PURCHASED: '<voice name="Brian"><lang xml:lang="en-GB"> Sorry glide was not purchased. </lang></voice>',
            THANK_YOU_FOR_BUYING: '<voice name="Brian"><lang xml:lang="en-GB"> Thanks for buying glide life line . </lang></voice>',
            CAN_NOT_BUY_CONSUMABLE: '<voice name="Brian"><lang xml:lang="en-GB"> It looks like we are unable to sell hints right now.  Sorry.  Please try again or start a new game.</lang></voice>',
            DEFAULT_GAME_NAME_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Please say,  create a new group to create a group to play. Or say, start a new game</lang></voice>',
            ERROR_CREATING_GROUP: '<voice name="Brian"><lang xml:lang="en-GB"> There was an error creating the group. Please try a single mode game. To start in single mode please say, Start single mode game. </lang></voice>',
            ERROR_CREATING_GROUP_REPEAT: '<voice name="Brian"><lang xml:lang="en-GB"> To start in single mode please say, Start single mode game. </lang></voice>',
            GROUP_ALREADY_EXISTS: '<voice name="Brian"><lang xml:lang="en-GB">  Sorry this group is already created. If you want to create a group with different name. Please say create a new group.  followed by the new group name .  Or, to play in this existing group say, compete with followed by Group Name. </lang></voice>',
            GROUP_ALREADY_EXISTS_REPROMPT: '<voice name="Brian"><lang xml:lang="en-GB">Please say, create a new group.  followed by new Group Name </lang></voice>',
            GROUP_NOT_EXISTS: '<voice name="Brian"><lang xml:lang="en-GB"> Thank you for creating a new group for your game. To start the game please say, start the game. </lang></voice>',
            GROUP_NOT_EXISTS_REPROMPT: '<voice name="Brian"><lang xml:lang="en-GB"> please say, start the game, to start playing.  </lang></voice>'

        }
    },
    de: {
        translation: {
            WELCOME_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Willkommen bei Millionaire Monkeys. In diesem Spiel geht es darum, Fragen zu verschiedenen Fähigkeiten zu lösen. Sie erhalten 15 Fragen und 3 Lebenslinien, die Ihnen beim Spielen helfen. Um ein neues Spiel zu starten, können Sie sagen, Sie starten ein neues Spiel, Sie starten eine Gruppe oder Sie spielen in einer Gruppe, Sie erstellen eine neue Gruppe, gefolgt von einem Gruppennamen, oder Sie spielen in einer vorhandenen Gruppe, gefolgt von einem Gruppennamen. Um mehr über die Lebenslinien in diesem Spiel zu erfahren, sagen wir, Lebenslinien. Sagen Sie, um Hilfe zu erhalten, Helfen Sie mir. Also, womit kann ich Ihnen helfen?</lang></voice>',
            WELCOME_BACK_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Willkommen zurück bei Millionaire Monkeys. Um das vorherige Spiel fortzusetzen, sagen Sie, setzen Sie das Spiel fort. Um ein neues Spiel zu starten, sagen Sie Neues Spiel starten. Wenn Sie beispielsweise in einer Gruppe spielen möchten, erstellen Sie eine neue Gruppe, gefolgt von einem Gruppennamen, oder spielen Sie in einer vorhandenen Gruppe, gefolgt von einem Gruppennamen. Sagen Sie, um Hilfe zu erhalten, Helfen Sie mir. Also, womit kann ich Ihnen helfen?</lang></voice>',
            WELCOME_REPROMPT_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Das habe ich nicht verstanden. Womit kann ich dir helfen?</lang></voice>',
            GOODBYE_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Auf Wiedersehen! Danke, dass du Millionaire Monkeys spielst</lang></voice>',
            REFLECTOR_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Sie haben gerade ausgelöst {{intentName}}</lang></voice>',
            FALLBACK_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Entschuldigung, das weiß ich nicht. Bitte versuche es erneut.</lang></voice>',
            ERROR_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Entschuldigung, ich hatte Probleme damit, das zu tun, worum Sie gebeten haben. Bitte versuche es erneut.</lang></voice>',
            CANNOT_BUY_RIGHT_NOW: '<voice name="Brian"><lang xml:lang="en-GB"> Ich glaube nicht, dass wir ein Produkt mit diesem Namen haben. Kannst du es nochmal versuchen?</lang></voice>',
            START_QUIZ_MESSAGE: '<voice name="Brian"><lang xml:lang="en-GB"> OKAY. Beginnen wir mit Millionaire Monkeys. </lang></voice>',
            CANNOT_CANCEL_RIGHT_NOW: '<voice name="Brian"><lang xml:lang="en-GB"> Beim Stornieren dieses Kaufs ist ein Problem aufgetreten. Bitte versuchen Sie es später noch einmal.</lang></voice>',
            ERROR_QUESTION_FETCH: '<voice name="Brian"><lang xml:lang="en-GB"> Beim Abrufen der Fragen ist ein Fehler aufgetreten. Sagen Sie bitte "Spiel fortsetzen" oder starten Sie ein neues Spiel, um fortzufahren! Oder Bitte versuchen Sie es später noch einmal</lang></voice>',
            QUESTION_BEGIN: '<voice name="Brian"><lang xml:lang="en-GB"> Um die Frage zu beantworten, sagen Sie bitte, Antwort ist, und dann Ihre Antwort . Hier ist Ihre Frage, die jetzt auftaucht. </lang></voice>',
            ALL_QUESTIONS_ANSWERED: '<voice name="Brian"><lang xml:lang="en-GB"> Glückwunsch! Sie haben alle Fragen beantwortet. Gut gemacht!</lang></voice>',
            QUESTIONS_ANSWERED_CORRECTLY: '<voice name="Brian"><lang xml:lang="en-GB"> Das ist die richtige Antwort. </lang></voice>',
            QUESTIONS_ANSWERED_WORNG: '<voice name="Brian"><lang xml:lang="en-GB"> ACH NEIN! Dies ist die falsche Antwort . </lang></voice>',
            NEXT_QUESTION: '<voice name="Brian"><lang xml:lang="en-GB"> Fahren wir mit Ihrer nächsten Frage fort. </lang></voice>',
            QUESTIONS_JUMP: '<voice name="Brian"><lang xml:lang="en-GB"> Sie können Ihre Gleitleine weiterhin kaufen und verwenden. Wenn Sie über diese Frage hinweggleiten möchten, sagen Sie bitte GLIDE life line kaufen. </lang></voice>', 
            QUESTIONS_CANNOT_JUMP: '<voice name="Brian"><lang xml:lang="en-GB"> Leider haben Sie Ihre GLIDE life line schon einmal benutzt. Dieses Spiel ist beendet . Bitte starte ein neues Spiel. </lang></voice>', 
            QUESTIONS_REPROMPT_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Das habe ich nicht verstanden.</lang></voice>' ,
            HELP_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Sie können die Option Fifty Fifty verwenden, um ein paar der richtigen und ein anderes Worng-Antworten anzuhören. ' 
            + ' Ihre andere Lebenslinie Expert Opinion kann Ihnen eine Anleitung für die richtige Antwort geben. '
            + ' Die dritte Lebensader GLIDE kann Sie durch falsche Antworten führen, aber Sie müssen GLIDE PACK kaufen </lang></voice>',
            CURRENT_SCORE: '<voice name="Brian"><lang xml:lang="en-GB"> Ihre aktuelle Punktzahl ist {{score}} . </lang></voice>',
            CURRENT_SCORE_ERROR: '<voice name="Brian"><lang xml:lang="en-GB">Bitte setzen Sie das Spiel fort oder starten Sie es, um den Spielstand zu erfahren.</lang></voice>',
            FIFTY_FITY_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Hier sind die beiden Optionen für Ihre Frage. </lang></voice>',
            EXPERT_REVIEW_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Dies ist, was der Experte zu Ihrer Frage zu sagen hat. </lang></voice>',
            LIFE_LINE_ERROR_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Entschuldigung, du kannst diese Lebenslinie nur benutzen, wenn dein Spiel läuft. Bitte setze das Spiel fort oder starte ein neues, um deine Lebenslinien zu nutzen. </lang></voice>',
            LIFE_LINE_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Du hast noch {{lifeLinesLeft}} Lebenslinien übrig. </lang></voice>',
            LIFE_LINE_EXHAUSTED: '<voice name="Brian"><lang xml:lang="en-GB"> Entschuldigung, Sie haben die Lebenslinie {{lifeLineName}} bereits verwendet. Bitte verwenden Sie eine andere Lebensader. </lang></voice>',
            LIFE_LINES_SATUS: '<voice name="Brian"><lang xml:lang="en-GB"> Um über andere Lebenslinien Bescheid zu wissen, geben Sie meinen Lebenslinien- oder Lebenslinienstatus an. </lang></voice>',
            CURRENT_QUESTION: '<voice name="Brian"><lang xml:lang="en-GB">Hier ist deine aktuelle Frage {{currentQuestion}} </lang></voice>',
            START_GAME_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Um das vorherige Spiel fortzusetzen, sagen Sie, "Spiel fortsetzen", oder um ein neues Spiel zu starten, sagen Sie, "Neues Spiel starten". Wenn Sie Hilfe benötigen, sagen Sie: Helfen Sie mir . Also, bei was kann ich Ihnen helfen?</lang></voice>',
            GAME_RULES_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> In diesem Spiel geht es darum, Fragen zu verschiedenen Fähigkeiten zu lösen. Sie erhalten 15 Fragen und 3 Lebenslinien, die Ihnen beim Spielen helfen. </lang></voice>',
            USE_LIFE_LINES: '<voice name="Brian"><lang xml:lang="en-GB"> Sie können jederzeit Fifty Fifty oder Expert Review oder Buy Glide Life Line verwenden. </lang></voice>',
            RESUME_ERROR_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Es tut uns leid, aber es gibt keine Spiele zum Fortsetzen. Um ein neues Spiel zu starten, sagen Sie Neues Spiel starten. Wenn Sie Hilfe benötigen, sagen Sie: Helfen Sie mir . Also, bei was kann ich Ihnen helfen?</lang></voice>',
            CONSUMABLE_NOT_PURCHASED: '<voice name="Brian"><lang xml:lang="en-GB"> Sorry Glide wurde nicht gekauft. </lang></voice>',
            THANK_YOU_FOR_BUYING: '<voice name="Brian"><lang xml:lang="en-GB"> Vielen Dank für den Kauf von glide life line.  {{askQuestion}}  </lang></voice>',
            CAN_NOT_BUY_CONSUMABLE: '<voice name="Brian"><lang xml:lang="en-GB"> Anscheinend können wir derzeit keine Tipps verkaufen. Entschuldigung . Bitte versuche es erneut oder starte ein neues Spiel.</lang></voice>',
            DEFAULT_GAME_NAME_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Bitte sagen Sie, erstellen Sie eine neue Gruppe, um eine Gruppe zum Spielen zu erstellen. Oder sagen Sie, starten Sie ein neues Spiel</lang></voice>',
            ERROR_CREATING_GROUP: '<voice name="Brian"><lang xml:lang="en-GB"> Beim Erstellen der Gruppe ist ein Fehler aufgetreten. Bitte versuchen Sie es mit einem Einzelmodus-Spiel . Um im Einzelmodus zu starten, sagen Sie, bitte "Einzelmodus-Spiel starten". </lang></voice>',
            ERROR_CREATING_GROUP_REPEAT: '<voice name="Brian"><lang xml:lang="en-GB"> Um im Einzelmodus zu starten, sagen Sie, bitte Start single mode game. </lang></voice>',
            GROUP_ALREADY_EXISTS: '<voice name="Brian"><lang xml:lang="en-GB">  Entschuldigung, diese Gruppe wurde bereits erstellt. Wenn Sie eine Gruppe mit einem anderen Namen erstellen möchten. Bitte sagen Sie eine neue Gruppe erstellen. gefolgt vom neuen Gruppennamen. Oder, um in dieser bestehenden Gruppe zu spielen, konkurrieren Sie mit, gefolgt von Gruppenname. </lang></voice>',
            GROUP_ALREADY_EXISTS_REPROMPT: '<voice name="Brian"><lang xml:lang="en-GB"> Bitte sagen Sie, erstellen Sie eine neue Gruppe, gefolgt von einem neuen Gruppennamen </lang></voice>',
            GROUP_NOT_EXISTS: '<voice name="Brian"><lang xml:lang="en-GB"> Vielen Dank, dass Sie eine neue Gruppe für Ihr Spiel erstellt haben. Bitte sagen Sie, um das Spiel zu starten, starten Sie das Spiel. </lang></voice>',
            GROUP_NOT_EXISTS_REPROMPT: '<voice name="Brian"><lang xml:lang="en-GB"> Bitte sagen Sie, starten Sie, das Spiel, um zu spielen.  </lang></voice>'
        }
    },
    ja: {
        translation: {
            WELCOME_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> ミリオネアモンキーズへようこそ。このゲームは、さまざまなスキルに関する質問を解決するものです。プレイ中に役立つ15の質問と3つのライフラインがあります。新しいゲームを開始するには、言う、新しいゲームを開始する、グループを開始する、またはグループでプレイする、たとえば、新しいグループを作成してからグループ名を付ける、または既存のグループでプレイしてからグループ名を付けることができます。このゲームのライフラインについて聞くには、ライフラインと言ってください。ヘルプについては、「助けて」と言ってください。だから、私は何であなたを助けることができますか？</lang></voice>',
            WELCOME_BACK_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> ミリオネアモンキーズへようこそ。前のゲームを再開するには、ゲームを再開してください。新しいゲームを開始するには、たとえば、新しいゲームを開始します。たとえば、グループでプレイするには、新しいグループを作成してからグループ名を入力するか、既存のグループでプレイしてからグループ名を入力します。ヘルプについては、「助けて」と言ってください。だから、私は何であなたを助けることができますか？</lang></voice>',
            WELCOME_REPROMPT_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> 聞き取れませんでした。私は何であなたを助けることができますか？</lang></voice>',
            GOODBYE_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> さようなら！ミリオネアモンキーズをプレイしていただきありがとうございます</lang></voice>',
            REFLECTOR_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> あなたはちょうどトリガーしました{{intentName}}</lang></voice>',
            FALLBACK_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> 申し訳ありませんが、それについては知りません。もう一度試してください。</lang></voice>',
            ERROR_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> 申し訳ありませんが、私はあなたが尋ねたことをするのに苦労しました。もう一度試してください。</lang></voice>',
            CANNOT_BUY_RIGHT_NOW: '<voice name="Brian"><lang xml:lang="en-GB"> その名前の製品があるとは思わない。再試行できますか？</lang></voice>',
            START_QUIZ_MESSAGE: '<voice name="Brian"><lang xml:lang="en-GB"> さぁ、始めよう 。 Millionaire Monkeys . </lang></voice>',
            CANNOT_CANCEL_RIGHT_NOW: '<voice name="Brian"><lang xml:lang="en-GB"> この購入のキャンセル中に問題が発生しました。しばらくしてからもう一度お試しください。</lang></voice>',
            ERROR_QUESTION_FETCH: '<voice name="Brian"><lang xml:lang="en-GB"> 質問の取得中にエラーが発生しました。ゲームを再開するか、新しいゲームを開始して続行してください！または、しばらくしてからもう一度お試しください</lang></voice>',
            QUESTION_BEGIN: '<voice name="Brian"><lang xml:lang="en-GB"> 質問に答えるために、答えは、そしてあなたの答えを言ってください、ここにあなたの質問が来ています。 </lang></voice>',
            ALL_QUESTIONS_ANSWERED: '<voice name="Brian"><lang xml:lang="en-GB"> おめでとうございます！すべての質問に答えました。あなたは億万長者の猿です。よくやった！  </lang></voice>',
            QUESTIONS_ANSWERED_CORRECTLY: '<voice name="Brian"><lang xml:lang="en-GB"> これは正しい答えです。 </lang></voice>',
            QUESTIONS_ANSWERED_WORNG: '<voice name="Brian"><lang xml:lang="en-GB"> 大野！これは間違った答えです。  </lang></voice>',
            NEXT_QUESTION: '<voice name="Brian"><lang xml:lang="en-GB"> 次の質問に進みましょう。 </lang></voice>',
            QUESTIONS_JUMP: '<voice name="Brian"><lang xml:lang="en-GB"> あなたはまだグライドライフラインを購入して使用することができます。この質問をすり抜けたい場合は、GLIDEライフラインを購入してください。 </lang></voice>', 
            QUESTIONS_CANNOT_JUMP: '<voice name="Brian"><lang xml:lang="en-GB"> 残念ながら、以前にGLIDEライフラインを使用したことがあります。このゲームは終了です。新しいゲームを始めてください。 </lang></voice>', 
            QUESTIONS_REPROMPT_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> 聞き取れませんでした。</lang></voice>' ,
            HELP_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> Fifty Fiftyオプションを使用して、いくつかの答えを1つずつ聞き、もう1つずつ着用することができます。 ' 
            + ' あなたの別のライフラインの専門家の意見はあなたに正しい答えのためのいくつかのガイダンスを提供することができます。 '
            + ' GLIDEの3番目のライフラインでは、間違った答えを見つけることができますが、GLIDE PACKを購入する必要があります </lang></voice>',
            CURRENT_SCORE: '<voice name="Brian"><lang xml:lang="en-GB"> 現在のスコアは{{score}}です。 </lang></voice>',
            CURRENT_SCORE_ERROR: '<voice name="Brian"><lang xml:lang="en-GB"> ゲームのスコアを知るには、ゲームを再開または開始してください。 </lang></voice>',
            FIFTY_FITY_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> 質問に対する2つのオプションがあります。 </lang></voice>',
            EXPERT_REVIEW_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> これはあなたの質問について専門家が言わなければならないことです。 </lang></voice>',
            LIFE_LINE_ERROR_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> 申し訳ありませんが、このライフラインはゲームの進行中にのみ使用できます。ライフラインを使用するには、新しいゲームを再開または開始してください。 </lang></voice>',
            LIFE_LINE_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> {{lifeLinesLeft}}のライフラインが残っています。 </lang></voice>',
            LIFE_LINE_EXHAUSTED: '<voice name="Brian"><lang xml:lang="en-GB"> 申し訳ありませんが、{{lifeLineName}}ライフラインを既に使用しています。別のライフラインを使用してください。 </lang></voice>',
            LIFE_LINES_SATUS: '<voice name="Brian"><lang xml:lang="en-GB"> 他のライフラインについて知るには、私のライフラインまたはライフラインのステータスを言ってください。 </lang></voice>',
            CURRENT_QUESTION: '<voice name="Brian"><lang xml:lang="en-GB">ここにあなたの現在の質問があります {{currentQuestion}} </lang></voice>',
            START_GAME_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> 前のゲームを再開するには「ゲームを再開」と言い、新しいゲームを開始するには「新しいゲームを開始」と言います。ヘルプについては、「助けて」と言ってください。だから、私は何であなたを助けることができますか？</lang></voice>',
            GAME_RULES_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> このゲームは、さまざまなスキルに関する質問を解決するものです。プレイ中に役立つ15の質問と3つのライフラインがあります。 </lang></voice>',
            USE_LIFE_LINES: '<voice name="Brian"><lang xml:lang="en-GB"> どの時点でも、フィフティフィフティを使用するか、エキスパートレビューを使用するか、グライドライフラインを購入することができます </lang></voice>',
            RESUME_ERROR_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> 再開するゲームはありません。新しいゲームを開始するには、たとえば、新しいゲームを開始します。ヘルプについては、「助けて」と言ってください。だから、私は何であなたを助けることができますか？</lang></voice>',
            CONSUMABLE_NOT_PURCHASED: '<voice name="Brian"><lang xml:lang="en-GB"> 申し訳ありませんが、グライドは購入されませんでした。 </lang></voice>',
            THANK_YOU_FOR_BUYING: '<voice name="Brian"><lang xml:lang="en-GB"> グライドライフラインをお買い上げいただきありがとうございます。  {{askQuestion}}  </lang></voice>',
            CAN_NOT_BUY_CONSUMABLE: '<voice name="Brian"><lang xml:lang="en-GB"> 現在、ヒントを販売できないようです。ごめんなさい。もう一度試すか、新しいゲームを開始してください。</lang></voice>',
            DEFAULT_GAME_NAME_MSG: '<voice name="Brian"><lang xml:lang="en-GB"> 新しいグループを作成して、プレイするグループを作成してください。または、新しいゲームを開始します</lang></voice>',
            ERROR_CREATING_GROUP: '<voice name="Brian"><lang xml:lang="en-GB"> グループの作成中にエラーが発生しました。シングルモードゲームをお試しください。シングルモードで開始するには、「シングルモードゲームを開始してください」と言ってください。 </lang></voice>',
            ERROR_CREATING_GROUP_REPEAT: '<voice name="Brian"><lang xml:lang="en-GB"> シングルモードで開始するには、「シングルモードゲームを開始してください」と言ってください。 </lang></voice>',
            GROUP_ALREADY_EXISTS: '<voice name="Brian"><lang xml:lang="en-GB">  このグループは既に作成されています。別の名前でグループを作成する場合。新しいグループを作成してください。新しいグループ名が続きます。または、この既存のグループでプレイするには、グループ名に続いて競争します。 </lang></voice>',
            GROUP_ALREADY_EXISTS_REPROMPT: '<voice name="Brian"><lang xml:lang="en-GB">新しいグループを作成してください。続いて新しいグループ名 </lang></voice>',
            GROUP_NOT_EXISTS: '<voice name="Brian"><lang xml:lang="en-GB"> ゲーム用の新しいグループを作成していただきありがとうございます。ゲームを開始するには、ゲームを開始してくださいと言ってください。 </lang></voice>',
            GROUP_NOT_EXISTS_REPROMPT: '<voice name="Brian"><lang xml:lang="en-GB"> ゲームを開始して、プレイを開始してください。  </lang></voice>'
        }
    }
}